import { TrashIcon } from '@heroicons/react/24/outline';
import { useDeleteTask } from '@lib/hooks';
import type { Task } from '@prisma/client';

type Props = {
  value: Task;
  optimistic?: boolean;
  onDeleted?: (id: string) => void; 
};

export default function TaskComponent({ value, optimistic, onDeleted }: Props) {
  // Optimistic model mutation generated by ZenStack; updates UI first and then confirms with server
  const { trigger: deleteTask } = useDeleteTask({ optimisticUpdate: true });

  // Delete handler: attempts to remove the Task and notifies parent so it can refresh state
  const onDelete = async () => {
    try {
      await deleteTask({ where: { id: value.id } });
      onDeleted?.(value.id);
    } catch (e) {
      // If any Todo references this Task, DB referential integrity (onDelete: Restrict) prevents deletion.
      // We surface a friendly message instead of crashing the UI.
      alert('Cannot delete: this task is used by an existing todo.');
    }
  };

  return (
    // Compact card layout for a single Task row
    <div className="border rounded-lg px-4 py-3 shadow-sm flex items-start justify-between w-full lg:w-[480px]">
      <div className="min-w-0">
        {/* Title with truncation to keep the row single-line where possible */}
        <div className="text-base font-medium truncate">{value.title}</div>
        {/* Optional description shown in a lighter style, also truncated */}
        {value.description && (
          <div className="text-sm opacity-70 truncate">{value.description}</div>
        )}
      </div>
      {/* Trash icon acts as the delete affordance; disabled-looking state while optimistic mutation is active */}
      <TrashIcon
        className={`w-5 h-5 ${
          optimistic ? 'text-gray-300 cursor-not-allowed' : 'text-gray-600 cursor-pointer'
        }`}
        onClick={() => {
          !optimistic && void onDelete();
        }}
      />
    </div>
  );
}
